version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  chatbot:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - qdrant
    volumes:
      - .:/app

volumes:
  qdrant_storage:
